server:
  port: 0 # assigns random port to instances of Settings API

spring:
  application:
    name: settings
  data:
    mongodb:
      host: settings-db
      port: 27017 # default mongo port
      database: settings

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true